version: '3.1'

services:
  drupal:
    image: drupal:8.2-apache
    ports:
      - 80:80
    volumes:
      - ./modules:/var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - sites_dir:/var/www/html/sites
    restart: always

  postgres:
    image: postgres:9.6    
    environment:
      POSTGRES_PASSWORD: test
    restart: always
volumes:
  sites_dir: